#!/usr/bin/env python3
"""
Phase 5 Servo Calibration Tool
================================
Communicates with ESP32 calibration mode (UDP port 9871)
to control servo angle/PWM in real-time and record calibration results.

Usage:
    python test/phase5_calibration.py              # auto-discover
    python test/phase5_calibration.py 192.168.0.10  # specify IP

Commands:
    set_angle <ch> <deg>    Move servo to specified angle (0~180 clamping)
    set_pwm <ch> <usec>     Direct PWM control (raw, no clamping)
    get_status              Query all channel states
    save_offset <ch> <usec> Record calibration offset (saves to calibration_log.json)
    sweep <ch>              Auto sweep test: 0->90->180->90->0
    help                    Show command list
    quit / exit             Exit
"""

import socket
import sys
import json
import os
import time
import tty
import termios
from datetime import datetime

# =============================================================
# Configuration
# =============================================================
UDP_PORT = 9871
TIMEOUT_SEC = 2.0
LOG_FILE = os.path.join(os.path.dirname(__file__), "calibration_log.json")
HEADER_FILE = os.path.join(os.path.dirname(__file__), "../include/servo_config.h")

# Channel-to-name mapping (channel number -> leg_joint)
CHANNEL_MAP = {
    0: "LF_HAA",  1: "LF_HFE",  2: "LF_KNE",
    3: "RF_HAA",  4: "RF_HFE",  5: "RF_KNE",
    6: "LH_HAA",  7: "LH_HFE",  8: "LH_KNE",
    9: "RH_HAA", 10: "RH_HFE", 11: "RH_KNE",
}


def get_channel_name(ch: int) -> str:
    return CHANNEL_MAP.get(ch, f"CH{ch}")


# =============================================================
# UDP Communication
# =============================================================
class CalibrationClient:
    def __init__(self, esp_ip: str):
        self.esp_ip = esp_ip
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.settimeout(TIMEOUT_SEC)
        print(f"[INFO] Target: {esp_ip}:{UDP_PORT}")

    def send_command(self, cmd: str) -> str:
        """Send command and receive response"""
        try:
            self.sock.sendto(cmd.encode(), (self.esp_ip, UDP_PORT))
            data, _ = self.sock.recvfrom(1024)
            return data.decode('utf-8', errors='replace')
        except socket.timeout:
            return "[TIMEOUT] No response from ESP32. Check WiFi connection / port."

    def close(self):
        self.sock.close()


# =============================================================
# Config & C++ Generator
# =============================================================
def load_log() -> dict:
    default_log = {"board_freq": 25000000, "offsets": {}, "history": []}
    if os.path.exists(LOG_FILE):
        try:
            with open(LOG_FILE, 'r') as f:
                data = json.load(f)
                if "board_freq" not in data:
                    data["board_freq"] = 25000000
                return data
        except Exception:
            pass
    return default_log

def generate_config_header(log: dict):
    # Ensure all 12 channels exist. If not, default to 0.0
    zero_offsets = [[0.0 for _ in range(3)] for _ in range(4)]
    for ch_str, entry in log.get("offsets", {}).items():
        ch = int(ch_str)
        leg = ch // 3
        jnt = ch % 3
        zero_offsets[leg][jnt] = entry.get("delta_deg", 0.0)
    
    board_freq = log.get("board_freq", 25000000)

    header_content = f"""#pragma once
#include <cstdint>

// This file is auto-generated by test/phase5_calibration.py
// DO NOT EDIT MANUALLY unless you know what you are doing.

constexpr uint32_t PCA9685_OSC_FREQ = {board_freq};

constexpr float ZERO_OFFSET[4][3] = {{
    {{{zero_offsets[0][0]:.2f}f, {zero_offsets[0][1]:.2f}f, {zero_offsets[0][2]:.2f}f}}, // LF
    {{{zero_offsets[1][0]:.2f}f, {zero_offsets[1][1]:.2f}f, {zero_offsets[1][2]:.2f}f}}, // RF
    {{{zero_offsets[2][0]:.2f}f, {zero_offsets[2][1]:.2f}f, {zero_offsets[2][2]:.2f}f}}, // LH
    {{{zero_offsets[3][0]:.2f}f, {zero_offsets[3][1]:.2f}f, {zero_offsets[3][2]:.2f}f}}  // RH
}};
"""
    with open(HEADER_FILE, 'w') as f:
        f.write(header_content)
    print(f"[CODEGEN] Updated {HEADER_FILE}")

def set_board_freq_log(freq: int):
    log = load_log()
    log["board_freq"] = freq
    with open(LOG_FILE, 'w') as f:
        json.dump(log, f, indent=2, ensure_ascii=False)
    generate_config_header(log)

def save_offset_to_log(ch: int, measured_us: float, response: str):
    log = load_log()
    ch_name = get_channel_name(ch)
    nominal_us = 1500.0  # 90 deg nominal
    delta_us = measured_us - nominal_us
    delta_deg = (delta_us / 2000.0) * 180.0

    entry = {
        "channel": ch,
        "name": ch_name,
        "measured_us": measured_us,
        "nominal_us": nominal_us,
        "delta_us": round(delta_us, 1),
        "delta_deg": round(delta_deg, 2),
        "timestamp": datetime.now().isoformat(),
    }

    log["offsets"][str(ch)] = entry
    log["history"].append(entry)

    with open(LOG_FILE, 'w') as f:
        json.dump(log, f, indent=2, ensure_ascii=False)

    print(f"[LOG] {ch_name} offset saved: delta={delta_us:+.0f}us ({delta_deg:+.1f} deg)")
    generate_config_header(log)


# =============================================================
# Jog Control
# =============================================================
def _read_key() -> str:
    """Read a single keypress (raw mode). Returns a string token."""
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        ch = sys.stdin.read(1)
        if ch == '\x1b':
            # Escape sequence — read up to 2 more bytes
            next1 = sys.stdin.read(1)
            if next1 == '[':
                next2 = sys.stdin.read(1)
                return f'\x1b[{next2}'   # e.g. '\x1b[A'
            return '\x1b'
        return ch
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)


def _us_to_deg(us: float) -> float:
    """Convert PWM microseconds to approximate angle (500us=0°, 2500us=180°)."""
    return (us - 500.0) / 2000.0 * 180.0


def run_jog(client: CalibrationClient, ch: int, start_us: float = 1500.0):
    """
    Interactive jog mode.

    Keys:
        ↑  / ↓   : ±10 us
        →  / ←   : ±1 us  (fine)
        S        : save_offset at current position
        Q / Esc  : exit jog mode
    """
    current_us = float(start_us)
    PWM_MIN, PWM_MAX = 500.0, 2500.0
    ch_name = get_channel_name(ch)

    print(f"\n[JOG] Channel {ch} ({ch_name})  start={int(current_us)}us")
    print("[JOG] ↑/↓ = ±10us   →/← = ±1us   S = save_offset   Q/Esc = quit\n")

    # Move to start position immediately
    client.send_command(f"set_pwm {ch} {current_us}")

    def _status_line():
        deg = _us_to_deg(current_us)
        return (f"\r[JOG] ch={ch} ({ch_name})  "
                f"PWM={int(current_us):4d}us  angle≈{deg:6.1f}°   "
                f"(↑↓±10  ←→±1  S=save  Q=quit)  ")

    sys.stdout.write(_status_line())
    sys.stdout.flush()

    while True:
        key = _read_key()

        if key == '\x1b[A':      # ↑
            delta = +10.0
        elif key == '\x1b[B':    # ↓
            delta = -10.0
        elif key == '\x1b[C':    # →
            delta = +1.0
        elif key == '\x1b[D':    # ←
            delta = -1.0
        elif key.lower() == 's':
            # Save offset at current position
            print()
            save_offset_to_log(ch, current_us, "")
            sys.stdout.write(_status_line())
            sys.stdout.flush()
            continue
        elif key.lower() in ('q', '\x1b', '\x03'):   # Q / Esc / Ctrl-C
            print(f"\n[JOG] Exited. Final PWM={int(current_us)}us "
                  f"(≈{_us_to_deg(current_us):.1f}°)")
            break
        else:
            continue

        new_us = current_us + delta
        if new_us < PWM_MIN:
            new_us = PWM_MIN
        elif new_us > PWM_MAX:
            new_us = PWM_MAX

        if new_us != current_us:
            current_us = new_us
            client.send_command(f"set_pwm {ch} {current_us}")
            sys.stdout.write(_status_line())
            sys.stdout.flush()


# =============================================================
# Sweep Test
# =============================================================
def run_sweep(client: CalibrationClient, ch: int):
    """Sequential move through 0->90->180->90->0 with pauses"""
    angles = [0, 45, 90, 135, 180, 135, 90, 45, 0]
    print(f"\n[SWEEP] Channel {ch} ({get_channel_name(ch)})")
    print(f"[SWEEP] Sequence: {' -> '.join(map(str, angles))}")
    print(f"[SWEEP] 1.5s pause at each position")
    print()

    for angle in angles:
        resp = client.send_command(f"set_angle {ch} {angle}")
        print(f"  -> {angle:3d} deg : {resp.strip()}")
        time.sleep(1.5)

    print(f"\n[SWEEP] Done.")

def run_sweep_pwm(client: CalibrationClient, ch: int, min_us: float, max_us: float):
    """Sequential move from min_us to max_us and back in steps of 5us"""
    print(f"\n[SWEEP_PWM] Channel {ch} ({get_channel_name(ch)})")
    print(f"[SWEEP_PWM] Sweeping from {int(min_us)} to {int(max_us)} in steps of 5us")
    print(f"[SWEEP_PWM] Press Ctrl+C to stop early (if needed)\n")

    pwms = []
    curr = min_us
    while curr <= max_us:
        pwms.append(curr)
        curr += 5.0
    
    # Add reverse path
    pwms.extend(pwms[-2::-1])

    try:
        for pwm_val in pwms:
            resp = client.send_command(f"set_pwm {ch} {pwm_val}")
            sys.stdout.write(f"\r  -> {int(pwm_val):4d} us : {resp.strip()}")
            sys.stdout.flush()
            time.sleep(1)  # 50ms for smooth motion
    except KeyboardInterrupt:
        print("\n[SWEEP_PWM] Interrupted by user.")

    print(f"\n[SWEEP_PWM] Done.")


# =============================================================
# Help Text
# =============================================================
HELP_TEXT = """
========================================================
  Phase 5 Servo Calibration Tool - Commands
========================================================

  set_angle <ch> <deg>         Move servo to angle (0-180 clamped)
  set_pwm <ch> <usec>          Direct PWM control (raw, no clamping)
  get_status                   Query all 12 channels
  save_offset <ch> <usec>      Record offset -> generates servo_config.h
  set_board_freq <freq>        Update board oscillator freq (e.g. 25000000)
  sweep <ch>                   Auto sweep angle: 0->90->180->90->0
  sweep_pwm <ch> <min> <max>   Auto sweep PWM: min->mid->max->mid->min
  jog <ch> [start_us]          Keyboard jog mode (↑↓±10us  ←→±1us  S=save  Q=quit)
  help                         Show this help
  quit / exit                  Exit

  Channel Map (ch -> Leg_Joint):
    0=LF_HAA  1=LF_HFE  2=LF_KNE
    3=RF_HAA  4=RF_HFE  5=RF_KNE
    6=LH_HAA  7=LH_HFE  8=LH_KNE
    9=RH_HAA 10=RH_HFE 11=RH_KNE
========================================================
"""


# =============================================================
# Main REPL
# =============================================================
def main():
    # Determine IP address
    if len(sys.argv) > 1:
        esp_ip = sys.argv[1]
    else:
        esp_ip = input("Enter ESP32 IP address (e.g. 192.168.0.10): ").strip()
        if not esp_ip:
            print("[ERROR] IP address is required.")
            sys.exit(1)

    client = CalibrationClient(esp_ip)

    # Connection test
    print("[INFO] Testing ESP32 connection...")
    resp = client.send_command("get_status")
    if "TIMEOUT" in resp:
        print(f"[WARN] {resp}")
        print("[WARN] Make sure ESP32 is in calibration mode.")
        print("[WARN]   Build: pio run -e esp32dev_calibration -t upload")
        proceed = input("Continue anyway? (y/n): ").strip().lower()
        if proceed != 'y':
            client.close()
            sys.exit(0)
    else:
        print("[OK] ESP32 responded.")
        print(resp)

    print(HELP_TEXT)

    # REPL loop
    while True:
        try:
            cmd = input("\n> ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\n[EXIT] Shutting down.")
            break

        if not cmd:
            continue

        # Local command handling
        if cmd.lower() in ("quit", "exit", "q"):
            print("[EXIT] Shutting down.")
            break
        elif cmd.lower() == "help":
            print(HELP_TEXT)
            continue
        elif cmd.lower().startswith("sweep_pwm"):
            parts = cmd.split()
            if len(parts) == 4:
                try:
                    ch = int(parts[1])
                    min_us = float(parts[2])
                    max_us = float(parts[3])
                    run_sweep_pwm(client, ch, min_us, max_us)
                except ValueError:
                    print("[ERROR] sweep_pwm <channel> <min_us> <max_us>")
            else:
                print("[ERROR] Usage: sweep_pwm <ch> <min_us> <max_us>")
            continue
        elif cmd.lower().startswith("jog"):
            parts = cmd.split()
            if len(parts) >= 2:
                try:
                    ch = int(parts[1])
                    start_us = float(parts[2]) if len(parts) >= 3 else 1500.0
                    run_jog(client, ch, start_us)
                except ValueError:
                    print("[ERROR] jog <channel> [start_us]")
            else:
                print("[ERROR] Usage: jog <ch> [start_us]")
            continue
        elif cmd.lower().startswith("sweep"):
            parts = cmd.split()
            if len(parts) == 2:
                try:
                    ch = int(parts[1])
                    run_sweep(client, ch)
                except ValueError:
                    print("[ERROR] sweep <channel_number>")
            else:
                print("[ERROR] Usage: sweep <channel>")
            continue

        # save_offset also saves locally
        if cmd.startswith("save_offset"):
            parts = cmd.split()
            if len(parts) == 3:
                try:
                    ch = int(parts[1])
                    usec = float(parts[2])
                    resp = client.send_command(cmd)
                    print(f"[ESP32] {resp}")
                    save_offset_to_log(ch, usec, resp)
                except ValueError:
                    print("[ERROR] save_offset <channel> <usec>")
            else:
                print("[ERROR] Usage: save_offset <channel> <usec>")
            continue
            
        if cmd.startswith("set_board_freq"):
            parts = cmd.split()
            if len(parts) == 2:
                try:
                    freq = int(parts[1])
                    resp = client.send_command(cmd)
                    print(f"[ESP32] {resp}")
                    set_board_freq_log(freq)
                except ValueError:
                    print("[ERROR] Frequency must be an integer (e.g., 25000000)")
            else:
                print("[ERROR] Usage: set_board_freq <freq>")
            continue

        # Send to ESP32
        resp = client.send_command(cmd)
        print(f"[ESP32] {resp}")

    client.close()


if __name__ == "__main__":
    main()
